import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const read = (file) => fs.readFileSync(path.join(root, file), "utf8");
const messages = read("screens/vendorMarketplaceMessagesScreen.js");
const bids = read("screens/vendorMarketplaceMyBidsScreen.js");
const applications = read("screens/vendorMarketplaceMyApplicationsScreen.js");
const awarded = read("screens/vendorMarketplaceAwardedBidsScreen.js");
const bidDetail = read("screens/vendorMarketplaceBidDetailScreen.js");
const applicationDetail = read("screens/vendorMarketplaceApplicationDetailScreen.js");
const eventVendorDetail = read("screens/eventVendorSubmissionDetailsScreen.js");
const foodMarketplace = read("screens/vendorMarketplaceNearMeScreen.js");
const eventVendorMarketplace = read("screens/eventVendorMarketplaceScreen.js");
const notificationBell = read("components/VendorMarketplaceNotificationBell.js");
const notificationHelper = read("helpers/marketplaceNotificationCenter.helper.js");
const api = read("api/appAPI.js");

assert.match(messages, /bid_id: bidId/);
assert.match(messages, /application_id: applicationId/);
assert.match(messages, /getMarketplaceMessageError/);
assert.match(messages, /questionText\.trim\(\)\.length < 3/);
assert.match(messages, /bid_id: bidId/);
assert.match(messages, /application_id: applicationId/);
assert.match(bids, /bidId: item\.bid_id/);
assert.match(applications, /applicationId: item\.application_id/);
assert.match(awarded, /bidId: item\.bid\?\.bid_id/);
assert.match(bidDetail, /MarketplaceImageViewer/);
assert.match(applicationDetail, /MarketplaceImageViewer/);
assert.match(eventVendorDetail, /Message Coordinator/);
assert.match(messages, /Unread Messages/);
assert.match(messages, /Read Messages/);
assert.match(messages, /Open Associated Event \/ Submission/);
assert.match(messages, /getMarketplaceMyBids_API/);
assert.match(messages, /getMarketplaceMyApplications_API/);
assert.match(messages, /getEventVendorApplications_API/);
assert.match(foodMarketplace, /VendorMarketplaceNotificationBell/);
assert.match(eventVendorMarketplace, /VendorMarketplaceNotificationBell/);
assert.match(notificationBell, /getMarketplaceNotificationRouteParams/);
assert.match(notificationBell, /Clear Notifications/);
assert.match(notificationHelper, /bidId: notification\?\.bid_id/);
assert.match(notificationHelper, /applicationId: notification\?\.application_id/);
assert.doesNotMatch(api, /new URLSearchParams\(\)/);
assert.match(api, /params,\s*\n\s*\}\);/);

console.log("vendor marketplace review and messaging tests passed");
